# Generated by Django 3.1.2 on 2020-11-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reasult1',
            fields=[
                ('groupname', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('votenum', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
